name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Cdebuginfo=0 --deny=warnings"
  RUSTDOCFLAGS: "--deny=warnings"

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: rustfmt
      - name: Check Formatting
        run: cargo +nightly fmt --all -- --check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ["1.65", stable, nightly]

    steps:
      - uses: actions/checkout@v3

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust_version }}
          components: clippy

      - name: Install system dependencies
        run: sudo apt-get install libxkbcommon-dev libwayland-dev

      - name: Run tests
        run: cargo test --verbose

      - name: Clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy -- -D warnings

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items
